import io
import streamlit as st

st.set_page_config(
    page_title="Policy AI System",
    page_icon="📜",
    layout="wide",
    initial_sidebar_state="collapsed",
)

import docx as python_docx
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from utils.summarizer import extractive_summarise, extract_key_metadata, auto_detect_name
from utils.generator import refine_summary, generate_policy_draft, PREDEFINED_SCENARIOS


# ── DOCX builders ───

def build_docx_summary(policy_name, summary_text, metadata):
    doc = python_docx.Document()
    t = doc.add_heading("Policy Summary Report", level=0)
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    t.runs[0].font.color.rgb = RGBColor(0x1A, 0x3C, 0x5E)
    doc.add_paragraph(f"Source Document: {policy_name}")
    doc.add_paragraph("")
    doc.add_heading("Document Statistics", level=2)
    tbl = doc.add_table(rows=1, cols=2)
    tbl.style = "Light List Accent 1"
    h = tbl.rows[0].cells; h[0].text = "Metric"; h[1].text = "Value"
    for lbl, val in [
        ("Source Word Count",     str(metadata.get("word_count", "—"))),
        ("Source Sentence Count", str(metadata.get("sentence_count", "—"))),
        ("Objectives Detected",   str(len(metadata.get("detected_objectives", [])))),
    ]:
        r = tbl.add_row().cells; r[0].text = lbl; r[1].text = val
    doc.add_paragraph("")
    doc.add_heading("Policy Summary", level=2)
    p = doc.add_paragraph(summary_text)
    p.runs[0].font.size = Pt(11)
    objs = metadata.get("detected_objectives", [])
    if objs:
        doc.add_paragraph("")
        doc.add_heading("Detected Policy Objectives", level=2)
        for o in objs:
            doc.add_paragraph(o.strip(), style="List Bullet")
    doc.add_paragraph("")
    f = doc.add_paragraph(
        "| Generated by Policy AI System | "
        "BSc Applied Data Science and Communication, KDU |"
    )
    f.runs[0].font.size = Pt(9)
    f.runs[0].font.color.rgb = RGBColor(0x99, 0x99, 0x99)
    buf = io.BytesIO(); doc.save(buf); return buf.getvalue()


def build_docx_draft(policy_name, sc_title, sc_desc, draft_text):
    doc = python_docx.Document()
    t = doc.add_heading("Adapted Policy Draft", level=0)
    t.alignment = WD_ALIGN_PARAGRAPH.CENTER
    t.runs[0].font.color.rgb = RGBColor(0x1A, 0x3C, 0x5E)
    doc.add_paragraph(f"Source Policy: {policy_name}")
    doc.add_paragraph(f"Scenario: {sc_title}")
    doc.add_paragraph("")
    doc.add_heading("Scenario Context", level=2)
    doc.add_paragraph(sc_desc)
    doc.add_paragraph("")
    doc.add_heading("Generated Policy Draft", level=2)
    for line in draft_text.split("\n"):
        s = line.strip()
        if not s:
            doc.add_paragraph("")
        elif s.startswith("##"):
            doc.add_heading(s.lstrip("#").strip(), level=3)
        elif s.startswith("#"):
            doc.add_heading(s.lstrip("#").strip(), level=2)
        elif s.startswith("**") and s.endswith("**"):
            p = doc.add_paragraph()
            p.add_run(s.strip("*")).bold = True
        else:
            doc.add_paragraph(s)
    doc.add_paragraph("")
    f = doc.add_paragraph(
        "| Generated by Policy AI System | "
        "BSc Applied Data Science and Communication, KDU |"
    )
    f.runs[0].font.size = Pt(9)
    f.runs[0].font.color.rgb = RGBColor(0x99, 0x99, 0x99)
    buf = io.BytesIO(); doc.save(buf); return buf.getvalue()


# ── PDF extraction ───

def extract_pdf_text(file_bytes):
    import pypdf
    reader = pypdf.PdfReader(io.BytesIO(file_bytes))
    return "\n".join(p.extract_text() or "" for p in reader.pages)


# ── Session state ───

def init_state():
    for k, v in {
        "policy_text": "", "policy_name": "",
        "extractive_raw": "", "summary": "",
        "metadata": {}, "drafts": {}, "active_drafts": [],
    }.items():
        if k not in st.session_state:
            st.session_state[k] = v


PILL_COLORS = ["🟢", "🩷", "🔵", "🟠"]


# ── Main ───

def main():
    init_state()

    # ── Header ────
    st.markdown("<h1 style='color:#064e3b'>📜 Policy AI System </h1>", unsafe_allow_html=True)
    st.caption(
        "**· Summarise real-world policy documents using NLP and generate "
        "scenario-adapted policy drafts powered by Generative AI ·**"
    )
    st.divider()

    # ── Two columns ───
    left, mid, right = st.columns([1, 0.015, 1], gap="small")
    with mid:
        st.markdown("<div style='border-left:2px solid #ccc;height:100%;min-height:600px;margin:auto;width:1px'></div>", unsafe_allow_html=True)

    # ══════════════════════════════════════════════════════════════════════════
    # LEFT — Input & Summarisation
    # ══════════════════════════════════════════════════════════════════════════
    with left:
        st.markdown("<h3 style='color:#4c1d95'>📄 Policy Input & Summarisation</h3>", unsafe_allow_html=True)
        st.caption("Upload a PDF or TXT file, or paste policy text directly.")

        # Document name
        doc_name = st.text_input(
            "Document name",
            value=st.session_state.policy_name,
            placeholder="Auto-detected when you upload or paste...",
        )
        if doc_name != st.session_state.policy_name:
            st.session_state.policy_name = doc_name

        input_mode = st.radio(
            "Input method",
            ["Paste text", "Upload file (PDF or TXT)"],
            horizontal=True,
        )

        if input_mode == "Paste text":
            pasted = st.text_area(
                "Paste policy text",
                height=200,
                placeholder="Paste the full policy document text here...",
                value=st.session_state.policy_text,
            )
            if pasted.strip() and pasted != st.session_state.policy_text:
                st.session_state.policy_text = pasted
                st.session_state.policy_name = auto_detect_name(pasted)
                st.rerun()
        else:
            uploaded = st.file_uploader("Upload PDF or TXT", type=["pdf", "txt"])
            if uploaded is not None:
                raw = uploaded.read()
                content = (
                    extract_pdf_text(raw)
                    if uploaded.name.lower().endswith(".pdf")
                    else raw.decode("utf-8", errors="replace")
                )
                if content != st.session_state.policy_text:
                    st.session_state.policy_text = content
                    st.session_state.policy_name = auto_detect_name(
                        content, filename=uploaded.name
                    )
                    st.rerun()
                st.success(
                    f"Loaded: **{uploaded.name}** — {len(st.session_state.policy_text):,} characters"
                )

        if st.session_state.policy_text:
            st.caption(f"Ready: {len(st.session_state.policy_text):,} characters loaded")

        num_sentences = st.slider(
            "key sentences",
            min_value=4, max_value=15, value=10, step=1,
            help="Number of sentences the NLP pipeline extracts before AI refinement.",
        )

        gen_btn = st.button(
            "Generate Summary",
            type="primary",
            disabled=not st.session_state.policy_text.strip(),
            use_container_width=True,
        )

        # Run pipeline
        if gen_btn:
            with st.spinner("Step 1 of 2 — NLP extraction (TF-IDF + MMR)..."):
                try:
                    raw = extractive_summarise(
                        st.session_state.policy_text,
                        num_sentences=num_sentences,
                    )
                    meta = extract_key_metadata(st.session_state.policy_text)
                    st.session_state.extractive_raw = raw
                    st.session_state.metadata = meta
                except Exception as e:
                    st.error(f"NLP extraction failed: {e}"); st.stop()

            with st.spinner("Step 2 of 2 — Generating the summary. Please wait..."):
                try:
                    refined = refine_summary(
                        extractive_sentences=raw,
                        policy_name=st.session_state.policy_name,
                    )
                    st.session_state.summary = refined
                    st.session_state.drafts = {}
                    st.session_state.active_drafts = []
                    st.success("Summary generated successfully.")
                except Exception as e:
                    st.error(f"AI refinement failed: {e}"); st.stop()

        # ── Summary output ───
        if st.session_state.summary:
            st.divider()
            st.markdown("<h3 style='color:#b45309'> Policy Summary</h3>", unsafe_allow_html=True)

            meta = st.session_state.metadata
            wc  = meta.get("word_count", 0)
            sc  = meta.get("sentence_count", 0)
            oc  = len(meta.get("detected_objectives", []))

            # 3 metric boxes
            m1, m2, m3 = st.columns(3)
            m1.metric("Source Words", f"{wc:,}")
            m2.metric("Source Sentences", sc)
            m3.metric("Objectives Found", oc)

            st.markdown("<style>div[data-testid='stAlert'] p {text-align: justify;}</style>", unsafe_allow_html=True)
            st.info(st.session_state.summary)

            # Detected objectives
            objs = meta.get("detected_objectives", [])
            if objs:
                with st.expander(f"Detected Policy Objectives ({len(objs)})"):
                    for i, obj in enumerate(objs, 1):
                        st.write(f"**{i}.** {obj.strip()}")


            # Downloads
            st.write("**Download Summary:**")
            safe = st.session_state.policy_name[:25].replace(" ", "_")
            d1, d2 = st.columns(2)
            with d1:
                st.download_button(
                    "⬇ Download .txt",
                    data=st.session_state.summary.encode("utf-8"),
                    file_name=f"summary_{safe}.txt",
                    mime="text/plain",
                    use_container_width=True,
                )
            with d2:
                st.download_button(
                    "⬇ Download .docx",
                    data=build_docx_summary(
                        st.session_state.policy_name,
                        st.session_state.summary,
                        st.session_state.metadata,
                    ),
                    file_name=f"summary_{safe}.docx",
                    mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    use_container_width=True,
                )

    # ══════════════════════════════════════════════════════════════════════════
    # RIGHT — Scenario Generation
    # ══════════════════════════════════════════════════════════════════════════
    with right:
        st.markdown("<h3 style='color:#7f1d1d'>🎯 Scenario-Based Policy Generation</h3>", unsafe_allow_html=True)
        st.caption(
            "Select a predefined scenario or define your own. Each draft is "
            "generated from the same summary, showing how one policy adapts "
            "to different real-world contexts."
        )

        if not st.session_state.summary:
            st.info("Generate a policy summary first (left panel) before creating scenario drafts.")
        else:
            st.info(
                "**Note:** Predefined scenarios are fully generic — they apply to any "
                "government policy document. The AI uses your specific summary to make "
                "each output relevant. For highly specific outputs, use 'Write my own scenario'."
            )

            mode = st.radio(
                "Scenario input mode",
                ["Use a predefined scenario", "Write my own scenario"],
                horizontal=True,
            )

            sc_title, sc_desc = "", ""

            if mode == "Use a predefined scenario":
                titles = [s["title"] for s in PREDEFINED_SCENARIOS]
                idx = st.selectbox(
                    "Select scenario",
                    range(len(titles)),
                    format_func=lambda i: titles[i],
                )
                sc = PREDEFINED_SCENARIOS[idx]
                sc_title = sc["title"]
                sc_desc  = sc["description"]
                st.success(f"**{sc_title}**")
                st.write(sc_desc)
            else:
                sc_title = st.text_input(
                    "Scenario title",
                    placeholder="e.g., Post-Conflict Reconstruction Policy",
                )
                sc_desc = st.text_area(
                    "Scenario description",
                    height=130,
                    placeholder=(
                        "Describe the context: what has changed, who the target audience is, "
                        "what constraints or new priorities apply..."
                    ),
                )

            can_generate = bool(
                st.session_state.summary and sc_title.strip() and sc_desc.strip()
            )

            if st.button(
                "Generate Policy Draft",
                type="primary",
                disabled=not can_generate,
                use_container_width=True,
            ):
                with st.spinner(f"Generating adapted draft for '{sc_title}'..."):
                    try:
                        draft = generate_policy_draft(
                            summary=st.session_state.summary,
                            scenario_title=sc_title,
                            scenario_description=sc_desc,
                        )
                        st.session_state.drafts[sc_title] = {
                            "title": sc_title,
                            "description": sc_desc,
                            "draft": draft,
                        }
                        if sc_title not in st.session_state.active_drafts:
                            st.session_state.active_drafts.append(sc_title)
                        st.success(f"Draft generated: '{sc_title}'")
                    except Exception as e:
                        st.error(f"Generation failed: {e}")

        # ── Generated drafts ───
        if st.session_state.active_drafts:
            st.divider()
            count = len(st.session_state.active_drafts)
            st.subheader(f"📝 Generated Drafts ({count})")
            st.caption("All drafts come from the same summary. Add more scenarios without re-summarising.")

            for i, dt in enumerate(st.session_state.active_drafts):
                dd = st.session_state.drafts.get(dt, {})
                if not dd: continue

                with st.container(border=True):
                    st.write(f"{PILL_COLORS[i % 4]} **{dt}**")
                    st.caption(f"{dd['description'][:160]}...")

                    with st.expander(
                        "View full policy draft",
                        expanded=(i == len(st.session_state.active_drafts) - 1),
                    ):
                        st.markdown(dd["draft"])

                    safe_dt = dt[:25].replace(" ", "_")
                    c1, c2, c3 = st.columns(3)
                    with c1:
                        st.download_button(
                            "⬇ .txt",
                            data=dd["draft"].encode("utf-8"),
                            file_name=f"draft_{safe_dt}.txt",
                            mime="text/plain",
                            use_container_width=True,
                            key=f"txt_{dt}",
                        )
                    with c2:
                        st.download_button(
                            "⬇ .docx",
                            data=build_docx_draft(
                                st.session_state.policy_name, dt,
                                dd["description"], dd["draft"],
                            ),
                            file_name=f"draft_{safe_dt}.docx",
                            mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            use_container_width=True,
                            key=f"docx_{dt}",
                        )
                    with c3:
                        if st.button("Remove", use_container_width=True, key=f"rm_{dt}"):
                            st.session_state.active_drafts.remove(dt)
                            del st.session_state.drafts[dt]
                            st.rerun()

    # ── Footer ───
    st.divider()
    st.caption(
        "**Policy AI System** · Data Science Applications and "
        "Artificial Intelligence · BSc Applied Data Science and Communication · "
        "General Sir John Kotelawala Defence University · Intake 41"
    )


if __name__ == "__main__":
    main()
